task_configs:
    - name: build_sources
      config_path: cloud/blockstore/sandbox/configs/task/nbs/cleanup/build_sources.yaml
    - name: run_test
      artifacts:
          - source_path: ''
            source_type: TEAMCITY_SERVICE_MESSAGES_LOG
            destination_path: ''
            destination_type: TEAMCITY_SERVICE_MESSAGES_LOG
      depends_on:
          - name: build_sources
            artifacts:
                - type: ARCADIA_PROJECT
                  parameter_name: test_binaries
