log:
  level: INFO
  add_stack_level: FATAL

server:
  listeners:
    - listener:
        tcp:
          port: 4435

front_envoy:
  downstream_http2_options:
    max_concurrent_streams: 100
    stream_window_bytes: 98304
    connection_window_bytes: 1048576

  upstream_http2_options:
    max_concurrent_streams: 100
    stream_window_bytes: 98304
    connection_window_bytes: 1048576

  hcm_options:
    use_remote_address: true

  listener_options:
    per_connection_buffer_limit_bytes: 98304

  tls_options:
    tls_minimum_protocol_version: TLSv1_2
